alert("Who create Java Script?")
alert("The father of JS is Brendan Eich")
alert("How many days Brendan Eich creating JS?")
alert("He create JS only 10 days")
alert("Which year created javascript")
alert("JavaScript was invented in 1995")
alert("Is JavaScript the same is Java?")
alert("No it is not. It is two different language.")
alert("What is the JS specification name?")
alert("First realise of JS specification is a ECMA-262")